### PR TITLE
WIP: Initial stab at some autogen

### PR DESCRIPTION
**Pull request by virtuald**
Leaving this here for now, I don't think I'll be able to get to it for awhile

* [x] Needs @auscompgeek 's sphinxify stuff
* [x] Constructors in simulation are broken
* [x] Compile errors in general (odd namespace things)
* [x] Deal with overloaded functions properly (have to specify via cast or lambda)

Closes: #1

### CODE REVIEW

**Comment by auscompgeek** [comment]
I've cleaned it up a little bit and added a sphinxify call.

Unfortunately CppHeaderParser concatenates Doxygen comments that are "next to" each other, so we'll also have to check whether it looks like that's happened and pick out the last one.

Still haven't fixed overloaded functions either. I don't currently want to think about how that'll work in simulation either.

This is also still missing the ExternalFollower type.

**Comment by auscompgeek** [comment]
Just realised I deliberately made sphinxify incompatible with Python 3.5.

I tried to get Travis CI to build the sdist with Python 3.6 first, like so:

```yaml
  - python: "3.5"
    install:
    # sphinxify doesn't support 3.5, so build the sdist using the system 3.6 first
    - /usr/bin/python3.6 -m pip install header2whatever sphinxify
    - /usr/bin/python3.6 setup.py sdist
    - pip install pytest coverage pytest-cov
    - "pip install dist/robotpy-rev-*.tar.gz"
```

... but unfortunately that didn't work.

I'm removing Python 3.5 from the CI config until we can come up with a solution (preferably one that doesn't involve me making another sphinxify release).

**Comment by auscompgeek** [comment]
Decided to ignore the problem of the overloaded methods. It seems to build now.

**Comment by auscompgeek** [comment]
I suspect the easiest way to get the overloaded functions working is to have an `overload: true` in the data, which the pybind11 template then checks and casts when specified. Simulation can then for now skip them and the methods can be added in `sim_class_extra`.

**Comment by auscompgeek** [comment]
Things that are missing now:
- follower mode and ExternalFollower type
- low-level methods
- exposing the sim data dict globally
- setSmartCurrentLimit sim implementation
- the below methods in sim
```
WARNING: CANSparkMax method SetSecondaryCurrentLimit missing
WARNING: CANSparkMax method IsFollower missing
WARNING: CANSparkMax method GetBusVoltage missing
WARNING: CANSparkMax method GetAppliedOutput missing
WARNING: CANSparkMax method GetOutputCurrent missing
```

I will probably try compiling and loading this in the afternoon.

Wonder whether lambdas would've been better than casting to handle the method overloads.

Open question: what key should the CANSparkMax sim data go under, and should the sim data keys be named to make implementing the low-level getParameter easier?

**Comment by virtuald** [comment]
I think casting is probably better, because there's no extra function call to elide (or not elide).

**Comment by auscompgeek** [comment]
Ah, that's true. Getting the correct return type is hard though.

**Comment by virtuald** [comment]
I'll take a look at this in the afternoon. It seems like it's probably good enough for an initial (heavily caveated) release though?

**Pull request merged**
