### PR TITLE
Updated robotcontainer.py and constants.py for the maxswerve example …

### PR DESCRIPTION
**Pull request by GitCloneHenry**
…to match updates to the commands2 class.

Hi, I'm Henry from team 9068, The Chargers. I realize that our previous fork was incorrect, so I updated our fork to be a direct fork of the repository rather than the singular example. Sorry for the confusion, let me know if you need to change anything.

### CODE REVIEW

**Comment by virtuald** [comment]
We can ignore the build failures because CI doesn't actually run the examples. Just make sure the check task succeeds and we're good to go here.

**Comment by GitCloneHenry** [comment]
I'll check them on real hardware later today, and I'll let you know if all the tests pass.

**Comment by GitCloneHenry** [comment]
Looks like the check task succeeded. Sorry it took so long, I've been balancing homework with programming recently, and CI is very particular.

**Comment by auscompgeek** [comment]
> CI is very particular.

It's not too particular, we just run [black](https://github.com/psf/black) to format the code.

**Comment by GitCloneHenry** [comment]
Thanks! I didn't realize that that was an option. I'll definitely use that in the future.

**Comment by virtuald** [comment]
Thanks!

**Pull request merged**
