### PR TITLE
Expose CANSparkMaxLowLevel

### PR DESCRIPTION
**Pull request by auscompgeek**
Builds on top of #11

### CODE REVIEW

**Comment by virtuald** [comment]
I'm not totally opposed to this, but it seems like it shouldn't be necessary?

**Comment by auscompgeek** [comment]
I could imagine there might be teams that wish to change the CAN frame periods, especially since it's suggested in the user manual if they want to read either position or velocity (can't remember which). We should allow that possibility.

**Comment by auscompgeek** [comment]
Hmm. Given that a real robot wouldn't be able to instantiate a CANSparkMaxLowLevel directly, I guess you shouldn't be able to do that in simulation either...

**Comment by auscompgeek** [comment]
Given the `RestoreFactoryDefaults` method in the beta is on `CANSparkMaxLowLevel`, I definitely think we should be exposing this.

**Review by virtuald — APPROVED** [review]
LGTM then

**Pull request merged**
